# Generated by Django 5.0.1 on 2024-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=250)),
                ("image", models.FileField(blank=True, upload_to="uploads/Equipments")),
            ],
        ),
    ]
