# Generated by Django 5.0.1 on 2024-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=250)),
                ("Image", models.FileField(blank=True, upload_to="uploads/Equipments")),
            ],
        ),
        migrations.DeleteModel(name="Equipments",),
    ]
