# Generated by Django 4.1.7 on 2024-01-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GymRegistration",
            fields=[
                ("gym_name", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
                ("owner_name", models.CharField(max_length=255)),
                ("instruments", models.TextField()),
                ("no_of_instructors", models.IntegerField(blank=True)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorRegistration",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                (
                    "cv_and_documents",
                    models.FileField(blank=True, upload_to="uploads/instructor"),
                ),
                (
                    "gmail",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("current_gym_gmail", models.EmailField(blank=True, max_length=254)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistration",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
    ]
