# Generated by Django 5.0.1 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymregistration",
            name="documents",
            field=models.FileField(blank=True, upload_to="uploads/gym_docs"),
        ),
    ]
