# Generated by Django 5.0.1 on 2024-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_equipment_delete_equipments"),
        ("Guest", "0002_gymregistration_documents"),
    ]

    operations = [
        migrations.RemoveField(model_name="gymregistration", name="instruments",),
        migrations.AddField(
            model_name="gymregistration",
            name="instruments",
            field=models.ManyToManyField(to="Admin.equipment"),
        ),
    ]
