# Generated by Django 5.0.1 on 2024-02-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymregistration",
            name="month_rate",
            field=models.FloatField(default=500),
        ),
    ]
