# Generated by Django 5.0.1 on 2024-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0005_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="msg",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="view_sts",
            field=models.IntegerField(default=0),
        ),
    ]
