# Generated by Django 5.0.1 on 2024-02-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
        ("Gym", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                ("slotid", models.IntegerField(primary_key=True, serialize=False)),
                ("startTime", models.CharField(max_length=50)),
                ("endTime", models.CharField(max_length=50)),
                (
                    "Substitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitution_slots",
                        to="Guest.userregistration",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_slots",
                        to="Guest.userregistration",
                    ),
                ),
            ],
        ),
    ]
