# Generated by Django 5.0.1 on 2024-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0002_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="slotid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
