# Generated by Django 5.0.1 on 2024-02-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
        ("Gym", "0004_slot_gym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="Substitution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substitution_slots",
                to="Guest.instructorregistration",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_slots",
                to="Guest.instructorregistration",
            ),
        ),
    ]
