# Generated by Django 5.0.1 on 2024-02-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
        ("Gym", "0005_alter_slot_substitution_alter_slot_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("status", models.IntegerField()),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.instructorregistration",
                    ),
                ),
            ],
        ),
    ]
