# Generated by Django 5.0.1 on 2024-02-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
        ("Gym", "0006_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="Gym",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Guest.gymregistration",
            ),
            preserve_default=False,
        ),
    ]
