# Generated by Django 5.0.1 on 2024-02-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0003_remove_gymregistration_instruments_and_more"),
        ("Gym", "0007_attendance_gym"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("body", models.CharField(max_length=1000)),
                ("date", models.DateField(blank=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.gymregistration",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.instructorregistration",
                    ),
                ),
            ],
        ),
    ]
