# Generated by Django 5.0.1 on 2024-02-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0008_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave", name="date", field=models.DateField(),
        ),
    ]
