# Generated by Django 5.0.1 on 2024-02-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0009_alter_leave_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot", name="seats", field=models.IntegerField(default=10),
        ),
    ]
