# Generated by Django 5.0.1 on 2024-02-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0004_gymregistration_month_rate"),
        ("Gym", "0010_slot_seats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("Bookid", models.AutoField(primary_key=True, serialize=False)),
                ("plan", models.IntegerField()),
                ("bookTime", models.DateTimeField(auto_now=True)),
                ("Startdate", models.DateField()),
                ("EndDate", models.DateField()),
                (
                    "cust",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.userregistration",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.gymregistration",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gym.slot",
                    ),
                ),
            ],
        ),
    ]
