# Generated by Django 5.0.1 on 2024-02-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0011_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workoutplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workouts", models.TextField(max_length=1000)),
                ("desc", models.TextField(max_length=100)),
                (
                    "remarkByTrainer",
                    models.TextField(default="No remark added", max_length=100),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "Bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Gym.book"
                    ),
                ),
            ],
        ),
    ]
