# Generated by Django 5.0.1 on 2024-02-22 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0012_workoutplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("status", models.IntegerField(default=0)),
                (
                    "bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Gym.book"
                    ),
                ),
            ],
        ),
    ]
