# Generated by Django 5.0.1 on 2024-02-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0013_slotbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="slotbooking",
            name="Slotid",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="Gym.slot"
            ),
            preserve_default=False,
        ),
    ]
