# Generated by Django 5.0.1 on 2024-02-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0004_gymregistration_month_rate"),
        ("Gym", "0014_slotbooking_slotid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Guest.instructorregistration",
            ),
        ),
    ]
