# Generated by Django 5.0.1 on 2024-04-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Guest", "0006_feedback_msg_alter_feedback_view_sts"),
        ("Gym", "0015_alter_job_employe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.IntegerField()),
                ("comment", models.CharField(max_length=100)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.gymregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Guest.userregistration",
                    ),
                ),
            ],
        ),
    ]
