# Generated by Django 5.0.1 on 2024-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gym", "0017_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="comment",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
